const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),{test}=require('node:test');
function api(){const window={},ctx={window,Date,Intl};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../diary-context.js'),'utf8'),ctx);return {core:window.DiaryContext,window};}
const point=()=>({latitude:55.9,longitude:36.8,accuracy:null,capturedAt:new Date().toISOString(),source:'manual',label:'Тестовая точка'});
const trip=()=>({version:1,point:point(),weather:null,gear:[{id:'rod-1',modelId:'test',name:'Удилище',category:'spinning',setup:{reel:'Катушка',line:'PE 0.6',leader:'Флюорокарбон'}}]});
test('missing context and empty snapshot stay empty; valid snapshots are detached',()=>{const {core}=api();assert.equal(core.normalize(),null);assert.equal(core.normalize({version:1,point:null,weather:null,gear:[]}),null);const input=trip(),out=core.normalize(input);input.gear[0].setup.line='изменено';assert.equal(out.gear[0].setup.line,'PE 0.6');});
test('invalid coordinates, model versions, timestamps and duplicate gear are rejected',()=>{const {core}=api();for(const change of [{point:{...point(),latitude:91}},{version:2},{point:{...point(),capturedAt:'today'}},{gear:[trip().gear[0],trip().gear[0]]}])assert.throws(()=>core.normalize({...trip(),...change}));});
test('device point must be fresh, explicitly from device and for today',()=>{const {core}=api();const s={mode:'device',status:'ready',name:'Место',point:{latitude:0,longitude:0,accuracy:10,timestamp:Date.now()}};assert.equal(core.devicePoint(s,core.today()).latitude,0);assert.throws(()=>core.devicePoint(s,'2000-01-01'));assert.throws(()=>core.devicePoint({...s,mode:'manual'},core.today()));assert.throws(()=>core.devicePoint({...s,point:{...s.point,timestamp:Date.now()-130000}},core.today()));});
test('past trip cannot issue weather requests; fresh point request keeps zero readings',async()=>{const {core,window}=api();let count=0;window.LiveWeather={freshFor:7200000,getPoint:async p=>{count++;assert.equal(p.id,'device');assert.equal(p.private,true);return {fetchedAt:Date.now(),data:{time:Date.now()/1000,timezone:'Europe/Moscow',temperature:0,feels:0,wind:0,direction:0,pressure:1013,code:0}};}};await assert.rejects(core.captureWeather(point(),'2000-01-01'));assert.equal(count,0);const w=await core.captureWeather(point(),core.today());assert.equal(w.temperature,0);assert.equal(w.wind,0);assert.equal(w.code,0);});
test('failed or stale conditions cannot become a saved weather snapshot',async()=>{const {core,window}=api();window.LiveWeather={freshFor:60000,getPoint:async()=>({error:'unavailable',data:{time:Date.now()/1000}})};await assert.rejects(core.captureWeather(point(),core.today()));window.LiveWeather.getPoint=async()=>({data:{time:Date.now()/1000-100}});await assert.rejects(core.captureWeather(point(),core.today()));});
test('weather of a different point and unknown fields are rejected',()=>{const {core}=api();const w={provider:'Open-Meteo',capturedAt:new Date().toISOString(),observedAt:new Date().toISOString(),latitude:60,longitude:36.8,timezone:'Europe/Moscow',temperature:10,feels:7,wind:3,direction:90,pressure:1000,code:3};assert.throws(()=>core.normalize({...trip(),weather:w}));assert.throws(()=>core.normalize({...trip(),secret:'x'}));});
